spring:
  banner:
    location: classpath:/banner.txt
    
management:
  endpoints:
    web:
      exposure:
        include: health, info , beans , env, *       
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
    beans:
      enabled: true